backend_test/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

from .utils.healthz import healthz

urlpatterns = [
    path("healthz", healthz, name="healthz"),
    #Se incluyen las rutas de la app delivery
    path('',include(("delivery.urls", "delivery"), namespace='delivery')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

delivery/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
 

urlpatterns = [
    # Path de control de sesión
    path('logout/', views.logoutpage,name='logout'),
    path('signin/', views.loginpage, name='loginpage'),

    # Path inicial
    path('menu/', views.main, name='main'),
    path('menu/<str:pk>', views.getMenu, name='get_menu'),

    # Path para el administrador
    path('create_menu/', views.createMenu, name='create_menu'),
    path('create_options/', views.createOptions, name='create_options'),
    path('create_dishes/', views.createDishes, name='create_dishes'),
    path('create_shopper/', views.createShopper, name="create_shopper"),

    # Path para órdenes
    path('create_order/<str:pk>/', views.createOrder, name='create_order'),
    path('edit_order/<str:pk>/', views.editOrder, name='edit_order'),
    path('drop_order/<str:pk>/', views.dropOrder, name='drop_order')
]

delivery/models.py
import datetime
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ManyToManyField
from .tasks import send_notification_shopper


class Shopper(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, blank=True, default='')
    phone = models.CharField(max_length=20, blank=True, default='')
    idSlack = models.CharField(max_length=20, blank=False, default='', unique=True)

    #Datos de control
    userAdd = models.ForeignKey(User, on_delete=CASCADE)
    dateAdd = models.DateField(auto_now_add=True)

    # Se da formato
    def __str__(self):
        return '%s UUID:  %s' % (self.name, self.id)

class MealPlate(models.Model):
    name = models.CharField('Name', max_length=100, blank=False, editable=True, default='')
    description = models.CharField('Description', max_length=250, blank=True, editable=True)
    price = models.FloatField("Price", default=0.0)
    available = models.BooleanField(default=True)
 
    # Datos de control
    userAdd = models.ForeignKey(User, on_delete=models.CASCADE)
    dateAdd = models.DateField(auto_now_add=True) 
    
    # Se da formato
    def __str__(self):
        return self.name

class Option(models.Model):
    name = models.CharField('Name', max_length=100, blank=False, editable=True, default='')
    description = models.CharField('Description', max_length=250, blank=True, editable=True)
    dishes = ManyToManyField(MealPlate)
    available = models.BooleanField(default=True)

    # Datos de control
    userAdd = models.ForeignKey(User, on_delete=models.CASCADE)
    dateAdd = models.DateField(auto_now_add=True) 

    # Se da formato
    def __str__(self):
        return '%s-%s' % (self.name, self.pk)

class DailyMenu(models.Model):
    dateDelivery = models.DateField(auto_now_add=True)
    name = models.CharField('Name', max_length=100, blank=False, editable=True, default='')
    description = models.CharField('Description', max_length=250, blank=True, editable=True)
    available = models.BooleanField(default=True)
    options = models.ManyToManyField(Option)

    # Se sobreescribe el método de guardado
    def save(self, *args, **kwargs):
        
        # Se obtiene la fecha actual
        today = datetime.date.today()
        
        # Se valída si el menú almacenado es el menú del día
        if self.dateAdd == today:
            
            # Si el menú guardado es el menú del día, se notifica a los compradores a través de la tarea 
            send_notification_shopper(Shopper.objects.all())
        # Se corre el guardado nativo    
        super(DailyMenu, self).save(*args, **kwargs)

    #Datos de control
    userAdd = models.ForeignKey(User, on_delete=models.CASCADE)
    dateAdd = models.DateField(auto_now_add=True) 

class Order(models.Model):
    shopper  = models.ForeignKey(Shopper, on_delete=CASCADE)
    option = models.ForeignKey(Option, on_delete=CASCADE)
    specifications = models.TextField(blank=True)
    deleted = models.BooleanField(default=False, editable=False)

    #Datos de control
    dateAdd = models.DateTimeField(auto_now_add=True)
    
    # Se da formato
    def __str__(self):
        return 'Order-%s' % (self.pk)



    
        

delivery/forms.py
from django import forms
import datetime
from django.db.models import fields

from .models import Shopper, Order, DailyMenu, Option, MealPlate

class ShopperForm(forms.ModelForm):

    class Meta:
        model = Shopper
        fields = ('name', 'phone')

class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ( 'shopper','option','specifications')

    def is_valid(self):
        # Validacción nativa
        valid = super(OrderForm, self).is_valid()
 
        # Si no es válido regresamos el dato
        if not valid:
            return valid

        # Verificación de horario
        currentHour = datetime.datetime.now().hour
        # Si la hora en la que se realiza la orden es superior a las 11am se debe indicar un error
        if currentHour > 11 :
            #Indica el error al form para plasmarlo en front
            self._errors['invalid_hour'] = 'Petición fuera de horario'
            return False
 
        # Todo bien, el formulario es válido
        return True


class DailyMenuForm(forms.ModelForm):
    class Meta:
        model = DailyMenu
        fields = ('name', 'description', 'options','available')
        
class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ('name', 'description', 'dishes')

class MealPlateForm(forms.ModelForm):
    class Meta:
        model = MealPlate
        fields = ('name', 'description', 'price')

delivery/views.py
from django.shortcuts import render, redirect
import datetime
from .models import Order, Shopper, DailyMenu, Option
from .forms import ShopperForm, DailyMenuForm, OptionForm, MealPlateForm, OrderForm
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Función para cerrar sessión
def logoutpage(request):
    #Función nativa de Django para cerrar sesión
    logout(request)

    #Una vez cerrada la sesión se redirecciona a la página principal
    return redirect("/menu/")

# Función para iniciar sesión con métodos nativos
def loginpage(request):
    # Si el método del request es POST se validan los datos recibidos
    if request.method == 'POST':
        # Se autenticann los datos enviados en el form a través de función nativa de Django
        user = authenticate(username=request.POST['username'],password=request.POST['password'])
        
        # Si la autentificación es correcta se inicia sesión del usuario
        if user:
            username = request.POST['username']
            request.session['username'] = username
            
            # Se inicia sesión a través de función nativa de Django
            login(request, user)

            # Una vez iniciada la sesión se redirecciona a la página principal 
            return redirect("/menu/")
        else:

            # Si la autentificación es incorrecta, se renderiza la página indicando el error
            return render(request, 'login.html', {"message":"Usuario o contraseña inválidos"})
    
    # Si el usuario está autenticado se redirecciona a la página principal
    if request.user.is_authenticated:
        return redirect("/menu/")
    
    #Si el usuario no está autentificado se renderiza la página de inicio de sesión
    else: 
        return render(request, 'login.html', {})

# Función para cargar la página inicial
def main(request):

    # Se obtiene el usuario dentro del request
    user = getattr(request, 'user', None)

    #Si el usuario que accede es "Nora" se le mostrarán las órdenes/pedidos de los demás usuarios 
    if user.username == 'nora':

        #Se obtienen todas las órdenes que no estén borradas lógicamente
        orders = Order.objects.filter(deleted=False)    

        #Se genera el contexto para renderizar el front
        context = {
            'user': user, 
            'orders': orders
        } 
        return render(request, 'orders.html', context)

    #Por el contrario, si el usuario no es "Nora" se renderiza el front de acceso denegado a las órdenes
    else:
        context = {'user': user,}
        return render(request, 'access.html', context)

# Fución que carga los pedidos realizados por el usuario que se identifica a través del UUID enviado a su slack
def getMenu(request,pk):
    # Se valida si el UUID enviado existe
    if Shopper.objects.filter(pk=pk).exists() :
        
        #Si existe se obtienen los datos del comprador
        shopper = Shopper.objects.get(pk=pk)
        
        #Se obtienen las órdenes del comprador que correspondan al día actual y que no estén borradas
        orderToday = Order.objects.filter(shopper=pk, dateAdd__date=datetime.date.today(), deleted=False)
        
        #Se genera la fecha de ayer
        time_threshold = datetime.date.today() - datetime.timedelta(days=1)

        #Se obtienen las órdenes anteriores al día de hoy. Esto a manera de mostrar un historia de órdenes
        orders = Order.objects.filter(shopper=pk, deleted=False, dateAdd__lte=time_threshold)
        
        # Se genera el contexto para realizar el renderizado
        context = {
            'shopper': shopper,
            'orderToday' : orderToday,
            'orders' : orders
        }
        return render(request, 'menu.html', context)
    
    # Si el UUID enviado NO existe se renderiza el front de acceso denegado
    else:
        return render(request, 'access.html', {})

#Función que le permite solo al administrador (Nora) crear un nuevo menú para el día actual
@login_required #Requiere estar autentificado
def createMenu(request):
    #Se valida si existe algún menú para el día actual
    dailyMenu = DailyMenu.objects.filter(dateAdd=datetime.date.today())
    
    #Si existe un menú para el día actual
    if dailyMenu:
        #Se obtiene dicho menú preexistente
        dailyToday = DailyMenu.objects.get(dateAdd=datetime.date.today())

        #Se genera un formulario pasando como instancia el menú preexistente
        form = DailyMenuForm(instance=dailyToday)
        
        #Si se recibe la instrucción de creación y ya existia ell menú, solo se actualiza instanciando el menú preexistente
        if request.method == "POST":
            form = DailyMenuForm(request.POST, instance=dailyToday)
            
            #Se valida el contenido del formulario
            if form.is_valid():
                #Si es correcto se guardan los cambios
                form.save()
            
            #Se regresa a la p+agina inicial
            return redirect('/menu/')
        #Si solo es la consulta se genera el contexto para renderizar y se envía un aviso de preexistencia 
        # aunado al menú preexistente
        else:
            context = {
                'form': form,
                'message': 'Ya existe un menu para el día de hoy, puedes modificarlo aquí',
                'menu':dailyMenu
                }
            return render(request, 'create_menu.html', context)
    
    #Si no existe menú preexistente y se recibe la instrucción de creación
    elif request.method == "POST":
        #Se genera formulario con los datos recibidos
        form = DailyMenuForm(request.POST)
        
        #Se valida que el formulario tenga los datos correctos
        if form.is_valid():
            
            #Si los datos son correctos se guarda el formulario
            post = form.save(commit=False)
            post.userAdd = request.user
            post.dateAdd = datetime.date.today()
            post.save()
            
            #Se redirecciona a la página principal
            return redirect('/menu/', pk=post.pk)
    #Si no existe un menú preexistente y no se recibe instrucción de crear uno se 
    # regresa el formulario corerspondiente a la creacion            
    else:
        #se genera el formulario de creación
        form = DailyMenuForm()
        #Se renderiza el formulario
        return render(request, 'create_menu.html', {'form': form})

#Función que permite crear opciones para los menus
@login_required #Requiere estar autentificado
def createOptions(request):
    #Si se recibe la instrucción de creación
    if request.method == "POST":
        #Se genera el formulario con los datos recibidos
        form = OptionForm(request.POST)
        if form.is_valid():
            #Si los datos son válidos se guarda el nuevo objeto
            post = form.save(commit=False)
            post.userAdd = request.user
            post.dateAdd = datetime.date.today() 
            post.save()
            return redirect('/menu/', pk=post.pk)
    else:
        #Si no se recibe instrucción de crear uno se 
        # regresa el formulario corerspondiente a la creacion      
        form = OptionForm()
    return render(request, 'create_option.html', {'form': form})

#Función que permite crear platillos para las opciones
@login_required #Requiere estar autentificado
def createDishes(request):
    #Si se recibe la instrucción de creación
    if request.method == "POST":
        #Se genera el formulario con los datos recibidos
        form = MealPlateForm(request.POST)
        if form.is_valid():
            #Si los datos son válidos se guarda el nuevo objeto
            post = form.save(commit=False)
            post.userAdd = request.user
            post.dateAdd = datetime.date.today()
            post.save()
            return redirect('/menu/', pk=post.pk)
    else:
        #Si no se recibe instrucción de crear uno se 
        # regresa el formulario corerspondiente a la creacion
        form = MealPlateForm()
    return render(request, 'create_meal_plate.html', {'form': form})

#Función que permite crear órdenes
def createOrder(request,pk):
    #Se obtiene el comprador dado el UUID enviado como pk
    shopper = Shopper.objects.get(pk=pk)
    
    #Se busca el menu para el día actual
    dailyMenu = DailyMenu.objects.filter(dateAdd=datetime.date.today()).values('id')
    
    #Si no existe un menú para el día actual se debe inidicar un error
    if not dailyMenu:
        return render(request, 'access.html')

    #Se obtienen las opciones asociadas al menú del día actual
    options = Option.objects.filter(dailymenu__id__in=dailyMenu)

    #Se inicializa un fomrulario con el comprador envíado por URI
    form = OrderForm(initial={'shopper':shopper})

    #Si se recibe la instrucción de creación
    if request.method == "POST":
        #Se crea un formulario con los datos recibidos
        formPost = OrderForm(request.POST)
        if formPost.is_valid():
            #Si el formulario es válido se guarda el nuevo objeto
            post = formPost.save(commit=False)
            post.dateAdd = datetime.date.today()
            post.save()
            return redirect('/menu/'+pk)
        else:
            #Se crea un formulario con los datos recibidos
            context = {'form':formPost, 'options': options}
            return render(request, 'create_order.html', context)
    else:
        #Si no se recibe instrucción de crear uno se 
        # regresa el formulario corerspondiente a la creacion
        context = {'form':form, 'options': options}
    return render(request, 'create_order.html', context)

#Función que permite editar una orden.
#No se usa para este momento
@login_required #Requiere estar autentificado
def editOrder(request,pk):
    order = Order.objects.get(id=pk)
    return render(request, 'access.html', {})

delivery/templates/access.html
{% extends 'base/home.html' %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Acceso denegado</h1>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">    

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <p>El acceso debe ser realizado desde la URL que llegó a tu Slack. Si aún no tienes la URL solicítala aquí.</p>
                <input type="text" placeholder="digita tu slack">
                <button>Solicitar URL</button>
                
            </div>
            <div class="card-body">
              <p>De lo contrario puedes iniciar sesión <a href="{% url 'delivery:loginpage'%}">aquí</a></p>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
</div>
{% endblock body %}

delivery/templates/create_meal_plate.html
{% extends 'base/home.html' %}
{% block body %}
<br>

    <h2>Crear platillo</h2>
	<br>

    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>



{% endblock body %}

delivery/templates/create_menu.html
{% extends 'base/home.html' %}
{% block body %}
<br>

    <h4>Crear menu para el día</h4>
	<br>
    {%if message%}
    <h4 style="color: red;">{{message}}</h4>
    <br>
    {%endif%}
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>
    


{% endblock body %}

delivery/templates/create_option.html
{% extends 'base/home.html' %}
{% block body %}
<br>

    <h2>Crear opción</h2>
	<br>

    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>


{% endblock body %}

delivery/templates/create_order.html
{% extends 'base/home.html' %}
{% block body %}
<br>
	<br>
    {%if message%}
    <h4 style="color: red;">{{message}}</h4>
    <br>
    {%endif%}
    <div class="row">
        <div class="col-12">    
          <div class="card">
            
            <div class="card-header">
                <h4>Menu del día</h4>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Opción</th>
                  <th>Descripción</th>
                  <th>Platillos</th>
                </tr>
                </thead>
                <tbody>
                    {% for option in options %}
                    <tr>
                      <td>{{ option.name }}</td>
                      <td>{{ option.description }}</td>
                      <td>
                        <ul>  
                      {% for dish in option.dishes.all %}
                            <li>{{dish.name}}</li>
                            {% endfor %}
                        </ul>
                      </td>
                      
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
    <br>
    
    <form method="POST">{% csrf_token %}
        <div class="fieldWrapper">
          <h4 style="color: red;">{{ form.errors.invalid_hour }}</h4>
        </div>
        <div class="fieldWrapper">
            {{ form.option.errors }}
            <label for="id_option">Option:</label>
            <select name="option" required="" id="id_option">
                <option value="" selected="">---------</option>
                {% for option in options %}
                <option value="{{option.id}}">{{option.name}}</option>
                {% endfor %}
              </select>
        </div>
        <div class="fieldWrapper">
            {{ form.specifications.errors }}
            <label for="id_specifications">Specifications:</label>
            <textarea name="specifications" cols="40" rows="10" id="id_specifications"></textarea>
        </div>
        <div class="fieldWrapper" hidden>
            {{form.shopper}}
        </div>
        
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>
    


{% endblock body %}

delivery/templates/create_shopper.html
{% extends 'base/home.html' %}
{% block body %}
<br>

    <h2>Nuevo cliente</h2>
	<br>
    <form method="POST" class="order-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>


{% endblock body %}

delivery/templates/delete_order.html
{% extends 'base/home.html' %}
{% block body %}
<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Estás por eliminiar la orden "{{order.id}}"?</p>

			<form action="{% url 'delivery:drop_order' order.id %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'delivery:main' %}">Cancelar</a>

				<button type="submit" class="btn btn-danger">Confirmar</button>
			</form>
		</div>
	</div>
</div>

{% endblock body %}

delivery/templates/login.html
{% extends 'base/home.html' %}
{% block body %}

<h2>Iniciar sesión</h2>
<br>
    {%if message%}
    <h4 style="color: red;">{{message}}</h4>
    <br>
    {%endif%}
    <form method="POST" id="add_form" action="{% url 'delivery:loginpage' %}">{% csrf_token %}
      <div class="row">
        <div class="col-lg-12">
          <input type="text" class="form-control mt-2" placeholder="Usuario" name="username" required>
        </div>
        <div class="col-lg-12">
          <input type="password" class="form-control mt-2" placeholder="Contraseña" name="password" required >
        </div>
        <div class="col-lg-12 mt-3">
          <button class="btn btn-primary btn-block" type="submit">Iniciar sesión</button>
        </div>
        {% if error %}
        <div class="col-lg-12 mt-2">
          <p style="color: #F46404;">{{error}}</p>
        </div>
        {% endif %}
      </div> 
    </form>
    
    


{% endblock body %}

delivery/templates/menu.html
{% extends 'base/home.html' %}
{% block body %}
<br>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Menú</h1>
              {% if shopper %}
              <h4>Hola {{ shopper.name }}</h4>
              {% endif %}
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">    

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              
              
              {% if orderToday|length %}
              <h4>Pedido de hoy </h4>
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Opción</th>
                    <th>Especificaciones</th>
                    <th>Platillos</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for order in orderToday %}
                    <td>{{ order.option }}</td>
                    <td>{{ order.specifications }}</td>
                    <td>
                      <ul>  
                        {% for dish in order.option.dishes.all %}
                          <li>{{dish.name}}</li>
                        {% endfor %}
                      </ul>
                    </td> 
                    {% endfor %}
                  </tr>    
                </tbody>
              </table>
              {% else %}
              <h4>Aún no cuentas con un pedido</h4>
              <br>
              <a class="btn btn-bg btn-info" href="{% url 'delivery:create_order' shopper.id %}">Realizar pedido</a>
              {% endif%}
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>


  {% if orders %}
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">    

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <h4>Órdenes previas</h4>
              
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Opción</th>
                    <th>Especificaciones</th>
                    <th>Platillos</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for order in orderToday %}
                    <td>{{ order.option }}</td>
                    <td>{{ order.specifications }}</td>
                    <td>
                      <ul>  
                        {% for dish in order.option.dishes.all %}
                          <li>{{dish.name}}</li>
                        {% endfor %}
                      </ul>
                    </td> 
                    {% endfor %}
                  </tr>    
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  {% endif %}

</div>
{% endblock body %}

delivery/templates/orders.html
{% extends 'base/home.html' %}
{% block body %}
<br>
<div id=modals></div>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Órdenes</h1>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">    

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Cliente</th>
                  <th>Platillos</th>
                  <th>Fecha de solicitud</th>
                </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                      <td>{{ order.shopper.name }}</td>
                      <td>
                        <ul>  
                          {% for dish in order.option.dishes.all %}
                            <li>{{dish.name}}</li>
                          {% endfor %}
                        </ul>
                      </td> 
                      <td>{{ order.dateAdd }}</td>
                      <td><a class="btn btn-sm btn-info" href="{% url 'delivery:edit_order' order.id %}">Editar</a></td>
                      <td><a class="btn btn-sm btn-danger" href="{% url 'delivery:drop_order' order.id %}">Borrar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
</div>



{% endblock body %}